# Preprocess dataset 
Combine each admission with patient info, diagnose ICD, procedure ICD and prescription

In [4]:
import getpass
user_id = getpass.getuser()

import sys
sys.path.append(f"/home/{user_id}/MIMIC-IV/")

import os 
import pandas as pd

In [5]:
base_path = f"/home/{user_id}/MIMIC-IV/"

In [6]:
admission_df = pd.read_csv(os.path.join(base_path, "hosp/admissions.csv"))
display(admission_df)

,subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admit_provider_id,admission_location,discharge_location,insurance,language,marital_status,race,edregtime,edouttime,hospital_expire_flag
0,10000032,22595853,2180-05-06 22:23:00,2180-05-07 17:15:00,NaN,URGENT,P874LG,TRANSFER FROM HOSPITAL,HOME,Other,ENGLISH,WIDOWED,WHITE,2180-05-06 19:17:00,2180-05-06 23:30:00,0
1,10000032,22841357,2180-06-26 18:27:00,2180-06-27 18:49:00,NaN,EW EMER.,P09Q6Y,EMERGENCY ROOM,HOME,Medicaid,ENGLISH,WIDOWED,WHITE,2180-06-26 15:54:00,2180-06-26 21:31:00,0
2,10000032,25742920,2180-08-05 23:44:00,2180-08-07 17:50:00,NaN,EW EMER.,P60CC5,EMERGENCY ROOM,HOSPICE,Medicaid,ENGLISH,WIDOWED,WHITE,2180-08-05 20:58:00,2180-08-06 01:44:00,0
3,10000032,29079034,2180-07-23 12:35:00,2180-07-25 17:55:00,NaN,EW EMER.,P30KEH,EMERGENCY ROOM,HOME,Medicaid,ENGLISH,WIDOWED,WHITE,2180-07-23 05:54:00,2180-07-23 14:00:00,0
4,10000068,25022803,2160-03-03 23:16:00,2160-03-04 06:26:00,NaN,EU OBSERVATION,P51VDL,EMERGENCY ROOM,NaN,Other,ENGLISH,SINGLE,WHITE,2160-03-03 21:55:00,2160-03-04 06:26:00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
431226,19999828,25744818,2149-01-08 16:44:00,2149-01-18 17:00:00,NaN,EW EMER.,P75BG6,TRANSFER FROM HOSPITAL,HOME HEALTH CARE,Other,ENGLISH,SINGLE,WHITE,2149-01-08 09:11:00,2149-01-08 18:12:00,0
431227,19999828,29734428,2147-07-18 16:23:00,2147-08-04 18:10:00,NaN,EW EMER.,P16C7J,PHYSICIAN REFERRAL,HOME HEALTH CARE,Other,ENGLISH,SINGLE,WHITE,2147-07-17 17:18:00,2147-07-18 17:34:00,0
431228,19999840,21033226,2164-09-10 13:47:00,2164-09-17 13:42:00,2164-09-17 13:42:00,EW EMER.,P58A9J,EMERGENCY ROOM,DIED,Other,ENGLISH,WIDOWED,WHITE,2164-09-10 11:09:00,2164-09-10 14:46:00,1
431229,19999840,26071774,2164-07-25 00:27:00,2164-07-28 12:15:00,NaN,EW EMER.,P506DE,EMERGENCY ROOM,HOME,Other,ENGLISH,WIDOWED,WHITE,2164-07-24 21:16:00,2164-07-25 01:20:00,0
431230,19999987,23865745,2145-11-02 21:38:00,2145-11-11 12:57:00,NaN,EW EMER.,P09IS0,EMERGENCY ROOM,REHAB,Other,ENGLISH,NaN,UNKNOWN,2145-11-02 19:28:00,2145-11-02 22:59:00,0

In [7]:
patient_df = pd.read_csv(os.path.join(base_path, "hosp/patients.csv"))
display(patient_df)

,subject_id,gender,anchor_age,anchor_year,anchor_year_group,dod
0,10000032,F,52,2180,2014 - 2016,2180-09-09
1,10000048,F,23,2126,2008 - 2010,NaN
2,10000068,F,19,2160,2008 - 2010,NaN
3,10000084,M,72,2160,2017 - 2019,2161-02-13
4,10000102,F,27,2136,2008 - 2010,NaN
...,...,...,...,...,...,...
299707,19999828,F,46,2147,2017 - 2019,NaN
299708,19999829,F,28,2186,2008 - 2010,NaN
299709,19999840,M,58,2164,2008 - 2010,2164-09-17
299710,19999914,F,49,2158,2017 - 2019,NaN
299711,19999987,F,57,2145,2011 - 2013,NaN

In [8]:
diagnoses_icd_df = pd.read_csv(os.path.join(base_path, "hosp/diagnoses_icd.csv"))
display(diagnoses_icd_df)

         subject_id   hadm_id  seq_num icd_code  icd_version
0          10000032  22595853        1     5723            9
1          10000032  22595853        2    78959            9
2          10000032  22595853        3     5715            9
3          10000032  22595853        4    07070            9
4          10000032  22595853        5      496            9
...             ...       ...      ...      ...          ...
4756321    19999987  23865745        7    41401            9
4756322    19999987  23865745        8    78039            9
4756323    19999987  23865745        9     0413            9
4756324    19999987  23865745       10    36846            9
4756325    19999987  23865745       11     7810            9

[4756326 rows x 5 columns]

In [9]:
# Aggregate diagnoses_icd_df with same hadm_id merged to one row
grouped_diagnoses_icd_df = diagnoses_icd_df.groupby("hadm_id")["icd_code"].agg(list).reset_index()
grouped_diagnoses_icd_df = grouped_diagnoses_icd_df.rename(columns={'icd_code': "diagnosis_icd_code"})
display(grouped_diagnoses_icd_df)

         hadm_id                                 diagnosis_icd_code
0       20000019  [0389, 59080, 75310, 5849, 2761, 99591, 25000,...
1       20000024  [D500, K521, I10, E538, M810, R270, Z9181, H54...
2       20000034  [K831, K8689, K861, K869, R1032, R10819, R8279...
3       20000041  [71536, 25002, V8541, 4019, 2724, V4586, 53081...
4       20000057  [71907, 71945, 99649, E8859, E8490, 4659, 4939...
...          ...                                                ...
430847  29999723  [4019, 340, 78830, E9478, 7804, 45981, 53081, ...
430848  29999745     [29680, 29620, 2720, 3019, V1541, 30981, V113]
430849  29999809  [41401, 03842, 5990, 99591, 5961, 496, 4111, 5...
430850  29999828  [27801, 5180, 2762, V8542, 4019, 2724, 25000, ...
430851  29999928  [I472, I723, I724, I452, E785, Z8249, Z8241, I...

[430852 rows x 2 columns]

In [10]:
procedures_icd_df = pd.read_csv(os.path.join(base_path, "hosp/procedures_icd.csv"))
display(procedures_icd_df)

        subject_id   hadm_id  seq_num   chartdate icd_code  icd_version
0         10000032  22595853        1  2180-05-07     5491            9
1         10000032  22841357        1  2180-06-27     5491            9
2         10000032  25742920        1  2180-08-06     5491            9
3         10000068  25022803        1  2160-03-03     8938            9
4         10000117  27988844        1  2183-09-19  0QS734Z           10
...            ...       ...      ...         ...      ...          ...
669181    19999840  21033226        5  2164-09-16     0331            9
669182    19999840  26071774        1  2164-07-25     8891            9
669183    19999840  26071774        2  2164-07-25     8841            9
669184    19999987  23865745        1  2145-11-07     8841            9
669185    19999987  23865745        2  2145-11-02     9671            9

[669186 rows x 6 columns]

In [11]:
# Aggregate procedures_icd_df with same hadm_id merged to one row
grouped_procedures_icd_df = procedures_icd_df.groupby("hadm_id")["icd_code"].agg(list).reset_index()
grouped_procedures_icd_df = grouped_procedures_icd_df.rename(columns={'icd_code': "procedure_icd_code"})
display(grouped_procedures_icd_df)

         hadm_id                                 procedure_icd_code
0       20000041                                             [8154]
1       20000069                                 [0KQM0ZZ, 10E0XZZ]
2       20000102                                       [7359, 7309]
3       20000147      [02100Z9, B211YZZ, 021209W, 06BQ4ZZ, 5A1221Z]
4       20000235                           [3723, 8856, 4523, 3995]
...          ...                                                ...
229440  29999444                                             [3893]
229441  29999560                                       [9671, 3893]
229442  29999625  [009630Z, 0B113F4, 5A1955Z, 0DH63UZ, 3E0G76Z, ...
229443  29999670                     [0066, 3606, 0046, 0041, 8856]
229444  29999828                                             [4438]

[229445 rows x 2 columns]

In [12]:
prescription_df = pd.read_csv(os.path.join(base_path, "hosp/prescriptions.csv"))
display(prescription_df)

/tmp/ipykernel_585905/1379783898.py:1: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  prescription_df = pd.read_csv(os.path.join(base_path, "hosp/prescriptions.csv"))

,subject_id,hadm_id,pharmacy_id,poe_id,poe_seq,order_provider_id,starttime,stoptime,drug_type,drug,...,gsn,ndc,prod_strength,form_rx,dose_val_rx,dose_unit_rx,form_val_disp,form_unit_disp,doses_per_24_hrs,route
0,10000032,22595853,11700683,10000032-34,34.0,P76JEQ,2180-05-07 01:00:00,2180-05-07 22:00:00,MAIN,Acetaminophen,...,004490,9.041989e+08,500mg Tablet,NaN,500,mg,1,TAB,NaN,PO/NG
1,10000032,22595853,14779570,10000032-22,22.0,P76JEQ,2180-05-07 00:00:00,2180-05-07 22:00:00,MAIN,Sodium Chloride 0.9% Flush,...,NaN,0.000000e+00,10 mL Syringe,NaN,3,mL,0.3,SYR,3.0,IV
2,10000032,22595853,19796602,10000032-50,50.0,P260SK,2180-05-08 08:00:00,2180-05-07 22:00:00,MAIN,Furosemide,...,008209,5.107901e+10,40mg Tablet,NaN,40,mg,1,TAB,1.0,PO/NG
3,10000032,22595853,20256254,10000032-32,32.0,P76JEQ,2180-05-07 01:00:00,2180-05-07 22:00:00,MAIN,Raltegravir,...,063231,6.022761e+06,400 mg Tablet,NaN,400,mg,1,TAB,2.0,PO
4,10000032,22595853,28781051,10000032-27,27.0,P76JEQ,2180-05-07 00:00:00,2180-05-07 22:00:00,MAIN,Heparin,...,006549,6.332303e+10,5000 Units / mL- 1mL Vial,NaN,5000,UNIT,1,mL,3.0,SC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15416703,19999987,23865745,92839339,19999987-25,25.0,P5542X,2145-11-03 00:00:00,2145-11-03 18:00:00,MAIN,Influenza Virus Vaccine,...,69637.0,3.333200e+10,0.5 mL Syringe,NaN,0.5,mL,1,SYR,0.0,IM
15416704,19999987,23865745,92913309,19999987-150,150.0,P63OX3,2145-11-04 10:00:00,2145-11-11 17:00:00,MAIN,Levothyroxine Sodium,...,6649.0,7.445521e+07,50mcg Tablet,NaN,50,mcg,1,TAB,1.0,PO/NG
15416705,19999987,23865745,95753195,19999987-219,219.0,P77Z1Y,2145-11-10 10:00:00,2145-11-11 17:00:00,MAIN,Duloxetine,...,57892.0,2.324033e+06,30mg Capsule,NaN,60,mg,2,CAP,1.0,PO
15416706,19999987,23865745,96343043,19999987-206,206.0,P77Z1Y,2145-11-09 10:00:00,2145-11-09 16:00:00,MAIN,Venlafaxine XR,...,46405.0,6.808405e+10,150mg XR Capsule,NaN,150,mg,1,CAP,1.0,PO
15416707,19999987,23865745,98044699,19999987-207,207.0,P77Z1Y,2145-11-09 10:00:00,2145-11-09 16:00:00,MAIN,Duloxetine,...,57892.0,2.324033e+06,30mg Capsule,NaN,60,mg,2,CAP,1.0,PO

In [13]:
# Aggregate prescription_df with same hadm_id merged to one row
grouped_prescription_df = prescription_df.groupby("hadm_id")["drug"].agg(list).reset_index()
display(grouped_prescription_df)

         hadm_id                                               drug
0       20000019  [Dextrose 50%, Acetaminophen, Aspirin, 0.9% So...
1       20000024  [Gabapentin, FoLIC Acid, Heparin, Acetaminophe...
2       20000034  [Bisacodyl, Insulin, Finasteride, Senna, Insul...
3       20000041  [HYDROmorphone (Dilaudid), Gabapentin, Hydroch...
4       20000057  [Multivitamins, Senna, Ipratropium Bromide Neb...
...          ...                                                ...
365437  29999723  [Heparin, Sodium Chloride 0.9%  Flush, Docusat...
365438  29999745  [traZODONE, Milk of Magnesia, traZODONE, Aceta...
365439  29999809  [0.9% Sodium Chloride (Mini Bag Plus), CefePIM...
365440  29999828  [Influenza Virus Vaccine, Influenza Virus Vacc...
365441  29999928  [Aspirin, OxyCODONE (Immediate Release), Senna...

[365442 rows x 2 columns]

In [14]:
# Combine admission, diagnoses_icd and procedures_icd
final_admission_df = admission_df.merge(patient_df, left_on='subject_id', right_on='subject_id')
final_admission_df = final_admission_df.merge(grouped_diagnoses_icd_df, left_on='hadm_id', right_on='hadm_id')
final_admission_df = final_admission_df.merge(grouped_procedures_icd_df, left_on='hadm_id', right_on='hadm_id')
display(final_admission_df)

,subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admit_provider_id,admission_location,discharge_location,insurance,...,edregtime,edouttime,hospital_expire_flag,gender,anchor_age,anchor_year,anchor_year_group,dod,diagnosis_icd_code,procedure_icd_code
0,10000032,22595853,2180-05-06 22:23:00,2180-05-07 17:15:00,NaN,URGENT,P874LG,TRANSFER FROM HOSPITAL,HOME,Other,...,2180-05-06 19:17:00,2180-05-06 23:30:00,0,F,52,2180,2014 - 2016,2180-09-09,"[5723, 78959, 5715, 07070, 496, 29680, 30981, ...",[5491]
1,10000032,22841357,2180-06-26 18:27:00,2180-06-27 18:49:00,NaN,EW EMER.,P09Q6Y,EMERGENCY ROOM,HOME,Medicaid,...,2180-06-26 15:54:00,2180-06-26 21:31:00,0,F,52,2180,2014 - 2016,2180-09-09,"[07071, 78959, 2875, 2761, 496, 5715, V08, 3051]",[5491]
2,10000032,25742920,2180-08-05 23:44:00,2180-08-07 17:50:00,NaN,EW EMER.,P60CC5,EMERGENCY ROOM,HOSPICE,Medicaid,...,2180-08-05 20:58:00,2180-08-06 01:44:00,0,F,52,2180,2014 - 2016,2180-09-09,"[07054, 78959, V462, 5715, 2767, 2761, 496, V0...",[5491]
3,10000068,25022803,2160-03-03 23:16:00,2160-03-04 06:26:00,NaN,EU OBSERVATION,P51VDL,EMERGENCY ROOM,NaN,Other,...,2160-03-03 21:55:00,2160-03-04 06:26:00,0,F,19,2160,2008 - 2010,NaN,[30500],[8938]
4,10000117,27988844,2183-09-18 18:10:00,2183-09-21 16:30:00,NaN,OBSERVATION ADMIT,P75S70,WALK-IN/SELF REFERRAL,HOME HEALTH CARE,Other,...,2183-09-18 08:41:00,2183-09-18 20:20:00,0,F,48,2174,2008 - 2010,NaN,"[S72012A, W010XXA, Y93K1, Y92480, K219, E7800,...",[0QS734Z]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229416,19999828,25744818,2149-01-08 16:44:00,2149-01-18 17:00:00,NaN,EW EMER.,P75BG6,TRANSFER FROM HOSPITAL,HOME HEALTH CARE,Other,...,2149-01-08 09:11:00,2149-01-08 18:12:00,0,F,46,2147,2017 - 2019,NaN,"[T8141XA, E1110, K632, D682, L02211, T83728A, ...","[0J980ZZ, 0WPF0JZ, 05HY33Z]"
229417,19999828,29734428,2147-07-18 16:23:00,2147-08-04 18:10:00,NaN,EW EMER.,P16C7J,PHYSICIAN REFERRAL,HOME HEALTH CARE,Other,...,2147-07-17 17:18:00,2147-07-18 17:34:00,0,F,46,2147,2017 - 2019,NaN,"[T8131XA, T8183XA, K632, D6851, N390, Y838, Y9...","[0HR7X74, 0HBJXZZ, 0HBHXZZ, 02HV33Z, 3E0436Z]"
229418,19999840,21033226,2164-09-10 13:47:00,2164-09-17 13:42:00,2164-09-17 13:42:00,EW EMER.,P58A9J,EMERGENCY ROOM,DIED,Other,...,2164-09-10 11:09:00,2164-09-10 14:46:00,1,M,58,2164,2008 - 2010,2164-09-17,"[3453, 51881, 5070, 5180, 42741, 43821, 43811,...","[9604, 9672, 966, 0331, 0331]"
229419,19999840,26071774,2164-07-25 00:27:00,2164-07-28 12:15:00,NaN,EW EMER.,P506DE,EMERGENCY ROOM,HOME,Other,...,2164-07-24 21:16:00,2164-07-25 01:20:00,0,M,58,2164,2008 - 2010,2164-09-17,"[43491, 43820, 34590, 43811, 4019, 2724, 3051]","[8891, 8841]"
229420,19999987,23865745,2145-11-02 21:38:00,2145-11-11 12:57:00,NaN,EW EMER.,P09IS0,EMERGENCY ROOM,REHAB,Other,...,2145-11-02 19:28:00,2145-11-02 22:59:00,0,F,57,2145,2011 - 2013,NaN,"[431, 3485, 20280, 5849, 5990, 2449, 41401, 78...","[8841, 9671]"

In [15]:
# Combine admission with prescription 
final_admission_df = final_admission_df.merge(grouped_prescription_df, left_on='hadm_id', right_on='hadm_id')
display(final_admission_df)

,subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admit_provider_id,admission_location,discharge_location,insurance,...,edouttime,hospital_expire_flag,gender,anchor_age,anchor_year,anchor_year_group,dod,diagnosis_icd_code,procedure_icd_code,drug
0,10000032,22595853,2180-05-06 22:23:00,2180-05-07 17:15:00,NaN,URGENT,P874LG,TRANSFER FROM HOSPITAL,HOME,Other,...,2180-05-06 23:30:00,0,F,52,2180,2014 - 2016,2180-09-09,"[5723, 78959, 5715, 07070, 496, 29680, 30981, ...",[5491],"[Acetaminophen, Sodium Chloride 0.9% Flush, F..."
1,10000032,22841357,2180-06-26 18:27:00,2180-06-27 18:49:00,NaN,EW EMER.,P09Q6Y,EMERGENCY ROOM,HOME,Medicaid,...,2180-06-26 21:31:00,0,F,52,2180,2014 - 2016,2180-09-09,"[07071, 78959, 2875, 2761, 496, 5715, V08, 3051]",[5491],"[Rifaximin, Lactulose, Calcium Carbonate, Furo..."
2,10000032,25742920,2180-08-05 23:44:00,2180-08-07 17:50:00,NaN,EW EMER.,P60CC5,EMERGENCY ROOM,HOSPICE,Medicaid,...,2180-08-06 01:44:00,0,F,52,2180,2014 - 2016,2180-09-09,"[07054, 78959, V462, 5715, 2767, 2761, 496, V0...",[5491],"[Albumin 25% (12.5g / 50mL), Calcium Carbonate..."
3,10000117,27988844,2183-09-18 18:10:00,2183-09-21 16:30:00,NaN,OBSERVATION ADMIT,P75S70,WALK-IN/SELF REFERRAL,HOME HEALTH CARE,Other,...,2183-09-18 20:20:00,0,F,48,2174,2008 - 2010,NaN,"[S72012A, W010XXA, Y93K1, Y92480, K219, E7800,...",[0QS734Z],"[Senna, Bisacodyl, Cepacol (Sore Throat Lozeng..."
4,10000560,28979390,2189-10-15 10:30:00,2189-10-17 15:00:00,NaN,SURGICAL SAME DAY ADMISSION,P08ZLF,PHYSICIAN REFERRAL,HOME,Other,...,NaN,0,F,53,2189,2008 - 2010,NaN,"[1890, V1582, V1201]",[5551],"[Scopolamine Patch, Ketorolac, Lorazepam, Pota..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220848,19999828,25744818,2149-01-08 16:44:00,2149-01-18 17:00:00,NaN,EW EMER.,P75BG6,TRANSFER FROM HOSPITAL,HOME HEALTH CARE,Other,...,2149-01-08 18:12:00,0,F,46,2147,2017 - 2019,NaN,"[T8141XA, E1110, K632, D682, L02211, T83728A, ...","[0J980ZZ, 0WPF0JZ, 05HY33Z]","[Insulin, Potassium Chloride, Insulin, Insulin..."
220849,19999828,29734428,2147-07-18 16:23:00,2147-08-04 18:10:00,NaN,EW EMER.,P16C7J,PHYSICIAN REFERRAL,HOME HEALTH CARE,Other,...,2147-07-18 17:34:00,0,F,46,2147,2017 - 2019,NaN,"[T8131XA, T8183XA, K632, D6851, N390, Y838, Y9...","[0HR7X74, 0HBJXZZ, 0HBHXZZ, 02HV33Z, 3E0436Z]","[Insulin, Potassium Chloride (Powder), Acetami..."
220850,19999840,21033226,2164-09-10 13:47:00,2164-09-17 13:42:00,2164-09-17 13:42:00,EW EMER.,P58A9J,EMERGENCY ROOM,DIED,Other,...,2164-09-10 14:46:00,1,M,58,2164,2008 - 2010,2164-09-17,"[3453, 51881, 5070, 5180, 42741, 43821, 43811,...","[9604, 9672, 966, 0331, 0331]","[Potassium Chloride, Bisacodyl, Phenytoin, 0.9..."
220851,19999840,26071774,2164-07-25 00:27:00,2164-07-28 12:15:00,NaN,EW EMER.,P506DE,EMERGENCY ROOM,HOME,Other,...,2164-07-25 01:20:00,0,M,58,2164,2008 - 2010,2164-09-17,"[43491, 43820, 34590, 43811, 4019, 2724, 3051]","[8891, 8841]","[Metoprolol Tartrate, Sodium Chloride 0.9% Fl..."
220852,19999987,23865745,2145-11-02 21:38:00,2145-11-11 12:57:00,NaN,EW EMER.,P09IS0,EMERGENCY ROOM,REHAB,Other,...,2145-11-02 22:59:00,0,F,57,2145,2011 - 2013,NaN,"[431, 3485, 20280, 5849, 5990, 2449, 41401, 78...","[8841, 9671]","[Bag, Magnesium Sulfate, Chlorhexidine Glucona..."

In [16]:
# Save the final admission dataframe into csv
final_admission_df.to_csv(os.path.join(base_path, 'hosp/final_admission.csv'), index=False, header=True)

In [17]:
# Read the saved dataframe to confirm
final_admission_df = pd.read_csv(os.path.join(base_path, 'hosp/final_admission.csv'))
display(final_admission_df)

,subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admit_provider_id,admission_location,discharge_location,insurance,...,edouttime,hospital_expire_flag,gender,anchor_age,anchor_year,anchor_year_group,dod,diagnosis_icd_code,procedure_icd_code,drug
0,10000032,22595853,2180-05-06 22:23:00,2180-05-07 17:15:00,NaN,URGENT,P874LG,TRANSFER FROM HOSPITAL,HOME,Other,...,2180-05-06 23:30:00,0,F,52,2180,2014 - 2016,2180-09-09,"['5723', '78959', '5715', '07070', '496', '296...",['5491'],"['Acetaminophen', 'Sodium Chloride 0.9% Flush..."
1,10000032,22841357,2180-06-26 18:27:00,2180-06-27 18:49:00,NaN,EW EMER.,P09Q6Y,EMERGENCY ROOM,HOME,Medicaid,...,2180-06-26 21:31:00,0,F,52,2180,2014 - 2016,2180-09-09,"['07071', '78959', '2875', '2761', '496', '571...",['5491'],"['Rifaximin', 'Lactulose', 'Calcium Carbonate'..."
2,10000032,25742920,2180-08-05 23:44:00,2180-08-07 17:50:00,NaN,EW EMER.,P60CC5,EMERGENCY ROOM,HOSPICE,Medicaid,...,2180-08-06 01:44:00,0,F,52,2180,2014 - 2016,2180-09-09,"['07054', '78959', 'V462', '5715', '2767', '27...",['5491'],"['Albumin 25% (12.5g / 50mL)', 'Calcium Carbon..."
3,10000117,27988844,2183-09-18 18:10:00,2183-09-21 16:30:00,NaN,OBSERVATION ADMIT,P75S70,WALK-IN/SELF REFERRAL,HOME HEALTH CARE,Other,...,2183-09-18 20:20:00,0,F,48,2174,2008 - 2010,NaN,"['S72012A', 'W010XXA', 'Y93K1', 'Y92480', 'K21...",['0QS734Z'],"['Senna', 'Bisacodyl', 'Cepacol (Sore Throat L..."
4,10000560,28979390,2189-10-15 10:30:00,2189-10-17 15:00:00,NaN,SURGICAL SAME DAY ADMISSION,P08ZLF,PHYSICIAN REFERRAL,HOME,Other,...,NaN,0,F,53,2189,2008 - 2010,NaN,"['1890', 'V1582', 'V1201']",['5551'],"['Scopolamine Patch', 'Ketorolac', 'Lorazepam'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220848,19999828,25744818,2149-01-08 16:44:00,2149-01-18 17:00:00,NaN,EW EMER.,P75BG6,TRANSFER FROM HOSPITAL,HOME HEALTH CARE,Other,...,2149-01-08 18:12:00,0,F,46,2147,2017 - 2019,NaN,"['T8141XA', 'E1110', 'K632', 'D682', 'L02211',...","['0J980ZZ', '0WPF0JZ', '05HY33Z']","['Insulin', 'Potassium Chloride', 'Insulin', '..."
220849,19999828,29734428,2147-07-18 16:23:00,2147-08-04 18:10:00,NaN,EW EMER.,P16C7J,PHYSICIAN REFERRAL,HOME HEALTH CARE,Other,...,2147-07-18 17:34:00,0,F,46,2147,2017 - 2019,NaN,"['T8131XA', 'T8183XA', 'K632', 'D6851', 'N390'...","['0HR7X74', '0HBJXZZ', '0HBHXZZ', '02HV33Z', '...","['Insulin', 'Potassium Chloride (Powder)', 'Ac..."
220850,19999840,21033226,2164-09-10 13:47:00,2164-09-17 13:42:00,2164-09-17 13:42:00,EW EMER.,P58A9J,EMERGENCY ROOM,DIED,Other,...,2164-09-10 14:46:00,1,M,58,2164,2008 - 2010,2164-09-17,"['3453', '51881', '5070', '5180', '42741', '43...","['9604', '9672', '966', '0331', '0331']","['Potassium Chloride', 'Bisacodyl', 'Phenytoin..."
220851,19999840,26071774,2164-07-25 00:27:00,2164-07-28 12:15:00,NaN,EW EMER.,P506DE,EMERGENCY ROOM,HOME,Other,...,2164-07-25 01:20:00,0,M,58,2164,2008 - 2010,2164-09-17,"['43491', '43820', '34590', '43811', '4019', '...","['8891', '8841']","['Metoprolol Tartrate', 'Sodium Chloride 0.9% ..."
220852,19999987,23865745,2145-11-02 21:38:00,2145-11-11 12:57:00,NaN,EW EMER.,P09IS0,EMERGENCY ROOM,REHAB,Other,...,2145-11-02 22:59:00,0,F,57,2145,2011 - 2013,NaN,"['431', '3485', '20280', '5849', '5990', '2449...","['8841', '9671']","['Bag', 'Magnesium Sulfate', 'Chlorhexidine Gl..."